### ISSUE TITLE
Implement knex models

### ISSUE THREAD

**Issue by floo51** [CaenCamp/usine-distribuee#2]

**Comment by tberriot** [comment]
@alexisjanvier considering [functional spec](https://docs.google.com/document/d/17xX1r_jxoFoo6wWzEdktw0jLRPkAwC-ttMIe5oCR68I/edit#heading=h.a57x87ofe9ak) and [first app mockup ](https://github.com/CaenCamp/usine-distribuee/pull/16) we need to add two fields on `request` table for `number of mask` and `number of day` about next request : see [DB doc review](https://docs.google.com/document/d/1TN9xHEDVXySSdt1AAX0wxRYDw5d9lPtJCBuZpYKKibk/edit#heading=h.e9igj1dpbz0e)
